### ISSUE TITLE
ClearTH build fails with an exception - errors in message.xsd

### ISSUE THREAD

**Issue by whynotu** [exactpro/clearth#1]
` Task :clearth-core:generateJavaFromXsd FAILED
[ant:xjc] [ERROR] s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
[ant:xjc]   line 2 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 
[ant:xjc] [ERROR] s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
[ant:xjc]   line 4 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 
[ant:xjc] [ERROR] s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw 'nginx'.
[ant:xjc]   line 5 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 
[ant:xjc] [ERROR] The element type "hr" must be terminated by the matching end-tag "</hr>".
[ant:xjc]   line 6 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Alex/Work/Tools/clearth-master/clearth-core/build.gradle' line: 19

* What went wrong:
Execution failed for task ':clearth-core:generateJavaFromXsd'.
> unable to parse the schema. Error messages should have been provided`

**Comment by Vladimir-Panarin-Exactpro** [comment]
Hi.
Can I have the command you executed? Which version of Gradle are you using?

**Comment by whynotu** [comment]
hi Vladimir, 

please see the command and full build log below. Gradle v5.5

`MacBook-Air:clearth-master Alex$ ./gradlew clean build publish

> Task :clearth-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :clearth-core:compileTestJava
Note: /Users/Alex/Work/clearth-master/clearth-core/src/test/java/com/exactprosystems/clearth/automation/SchedulerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :clearth-modules:clearth-swift:generateJavaFromXsd FAILED
[ant:xjc] [ERROR] s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
[ant:xjc]   line 2 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 
[ant:xjc] [ERROR] s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
[ant:xjc]   line 4 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 
[ant:xjc] [ERROR] s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw 'nginx'.
[ant:xjc]   line 5 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 
[ant:xjc] [ERROR] The element type "hr" must be terminated by the matching end-tag "</hr>".
[ant:xjc]   line 6 of http://exactpro.com/clearth/message/message.xsd
[ant:xjc] 

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Alex/Work/clearth-master/clearth-modules/clearth-swift/build.gradle' line: 22

* What went wrong:
Execution failed for task ':clearth-modules:clearth-swift:generateJavaFromXsd'.
> unable to parse the schema. Error messages should have been provided

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
25 actionable tasks: 19 executed, 6 up-to-date
`

**Comment by Vladimir-Panarin-Exactpro** [comment]
Thank you.
I can see this issue only when _clearth-core/xsd/message.cat_ is absent or when I modify _clearth-modules/clearth-swift/build.gradle_ to point to unexpected location of _message.cat_.

Haven't you modified any files of the project? Probably, some files are missing. Please check that _clearth-core/xsd/message.cat_ is present.

**Comment by whynotu** [comment]
> Thank you.
> I can see this issue only when _clearth-core/xsd/message.cat_ is absent or when I modify _clearth-modules/clearth-swift/build.gradle_ to point to unexpected location of _message.cat_.
> 
> Haven't you modified any files of the project? Probably, some files are missing. Please check that _clearth-core/xsd/message.cat_ is present.

I didn't change any of the files or their location. _message.cat_ is in place and file locations in _build.gradle_ seem correct however the issue still occurs. As I see the error text refers to message.xsd ill format.

**Comment by whynotu** [comment]
I have resolved it by swapping _xmlns_ and _targetNamespace_ definitions in message.xsd. It makes sense because artefacts can't be defined before the actual name space that keeps them.

before:
```
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
			jaxb:version="2.1"
                        xmlns="http://exactpro.com/clearth/message"
			targetNamespace="http://exactpro.com/clearth/message">
			
```

after:
```
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
			jaxb:version="2.1"
			targetNamespace="http://exactpro.com/clearth/message"
			xmlns="http://exactpro.com/clearth/message">
```

**Comment by Vladimir-Panarin-Exactpro** [comment]
Ok, thank you for these details.
